require.config({
    baseUrl: '/statics/exam/',
    paths:{
	  "mod/react": "/statics/exam/mod/react",
	  "mod/ReactRouter": "/statics/exam/mod/ReactRouter",
	  "lib/es5-shim": "/statics/exam/lib/es5-shim",
	  "lib/es5-sham": "/statics/exam/lib/es5-sham",
	  "lib/PubSubJS": "/statics/exam/lib/PubSubJS",
	  "lib/ReactRouter": "/statics/exam/lib/ReactRouter",
	  "components/InputEle.jsx": "/statics/exam/components/InputEle",
	  "components/AlertModal.jsx": "/statics/exam/components/AlertModal",
	  "components/Loading.jsx": "/statics/exam/components/Loading",
	  "components/CheckRadio.jsx": "/statics/exam/components/CheckRadio",
	  "lib/zepto.min": "/statics/exam/lib/zepto.min",
	  "components/Modal.jsx": "/statics/exam/components/Modal",
	  "components/ScrollList.jsx": "/statics/exam/components/ScrollList",
	  "components/Tabs.jsx": "/statics/exam/components/Tabs",
	  "jquery": "/statics/exam/lib/jquery",
	  "lib/jquery": "/statics/exam/lib/jquery",
	  "plus/jqExtend": "/statics/exam/plus/jqExtend",
	  "site/index.jsx": "/statics/exam/site/index",
	  "site/login.jsx": "/statics/exam/site/login",
	  "site/reg.jsx": "/statics/exam/site/reg",
	  "site/type.jsx": "/statics/exam/site/Type",
	  "site/Exam.jsx": "/statics/exam/site/Exam",
	  "site/Type_ExamAllList.jsx": "/statics/exam/site/Type_ExamAllList",
	  "site/Type_exam.jsx": "/statics/exam/site/Type_exam",
	  "site/Type_User.jsx": "/statics/exam/site/Type_User",
	  "site/formalList.jsx": "/statics/exam/site/formalList",
	  "site/testList.jsx": "/statics/exam/site/testList",
	  "site/questionsList.jsx": "/statics/exam/site/questionsList"
	}
});